apiVersion: apps/v1
kind: Deployment
metadata:
  name: edw-nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edw-nginx-proxy
  template:
    metadata:
      labels:
        app: edw-nginx-proxy
    spec:
      containers:
      - name: edw-nginx-proxy
        image: nginx:latest
        ports:
        - containerPort: 80
          name: nginx-main
        - containerPort: 1521
          name: internal-input
        volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-conf
      volumes:
        - name: nginx-conf
          hostPath:
            type: File
            path: /Users/a80099709/Desktop/docker_data/nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: edw-nginx-proxy-main 
  annotations: {
    "UseCase": "nginx check"
  }    
spec:
  type: ClusterIP
  selector:
    app: edw-nginx-proxy
  ports:
  - name: nginx-main
    protocol: TCP
    port: 8081
    targetPort: 1521

---
apiVersion: v1
kind: Service
metadata:
  name: edw-nginx-proxy-input
  annotations: {
    "UseCase": "Test in DBeaver"
  }    
spec:
  type: NodePort
  selector:
    app: edw-nginx-proxy
  ports:
  - name: nginx-main
    protocol: TCP
    port: 1521
    targetPort: 1521
    nodePort: 32000