apiVersion: apps/v1
kind: Deployment
metadata:
  name: only-nginx-deployment
  annotations:
    kubernetes.io/change-cause: v1.19.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: only-nginx-deployment
  template:
    metadata:
      labels:
        app: only-nginx-deployment
    spec:
      containers:
      - name: only-nginx-deployment
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: only-nginx-deployment-svc
spec:
  type: ClusterIP
  selector:
    app: only-nginx-deployment
  ports:
  - port: 8080
    targetPort: 80
