apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webapp-mysql
  name: webapp-mysql
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    name: webapp-mysql
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
