apiVersion: v1
kind: Pod
metadata:
  name: k-sim-app
  labels:
    name: k-sim-app
spec:
  containers:
  - name: k-sim-app
    image: arisu1000/simple-container-app:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    env:
      - name: TESTENV01
        value: "testvalue01"
      - name: HOSTNAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: CPU_REQUEST
        valueFrom:
          resourceFieldRef:
            containerName: k-sim-app
            resource: requests.cpu
      - name: CPU_LIMIT
        valueFrom:
          resourceFieldRef:
            containerName: k-sim-app
            resource: limits.cpu

            