# controller

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deploy
  labels:
      app: ngnix-app
spec:
  replicas: 3 #RC/RS definition - replication controller/replica set
  selector:
    matchLabels:
      app: nginx-app

  template: # pod template/definition starts here
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app

    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
            
